### ISSUE TITLE
UIP enhancements

### ISSUE THREAD

**Issue by EyalLavi** [ebu/ebu-tt-live-toolkit#180]
This issue is a placeholder for UIP subtasks that were not completed in Release 2. 

As a developer/tester, I want a sequence of part 3 documents generated from text input so that I can develop/test an implementation against it.

Input: Text provided by user.
Output: Sequence of EBU-TT Live documents.

Remaining tasks:
- [ ] Allow text to be added in one of two regions #117
- [ ]  Add handling of facets #115
- [ ] Handle the possibility to add elements (div, p, span) to the body of the document #116
- [ ] Handle bug #123

**Comment by EyalLavi** [comment]
@nigelmegitt I'm assuming this is for post-publication (R > 3) but is it a nice to have as well?

**Comment by nigelmegitt** [comment]
Yes to both of those. I don't mind this creeping into R3 if we have time and effort.
