### ISSUE TITLE
COMPONENT: Handover node

### ISSUE THREAD

**Issue by EyalLavi** [ebu/ebu-tt-live-toolkit#26]
As a subtitle provider/broadcaster, I want to combine documents from alternating respeakers/stenographers into a single EBU-TT live 

Input: 2 or more part 3 sequences; handover options.
Output: a single part 3 sequence.

Subtasks:

 -  [x] Implement core functionality #363 
 -  [x] Create configurator #368 
 -  [x] Document handover node #364
 -  [x] Unittest handover node #373 
 -  [x] BDD testing for handover node #397 (duplicate of #311) 
 -  [x] UIP modifications to support handover use-case #374

**Comment by nigelmegitt** [comment]
Note that Handover Node is a specialised form of Switcher Node - see comment on #28.

**Comment by EyalLavi** [comment]
I believe this can be closed now as all sub-tasks are completed and merged.
