### ISSUE TITLE
COMPONENT: Delay node

### ISSUE THREAD

**Issue by EyalLavi** [ebu/ebu-tt-live-toolkit#27]
As a playout service provider, I want to add a delay to the sequence so that I can synchronise subtitle with audio.

Input: a sequence of part 3 documents.
Output: a delayed sequence of part 3 documents.
- [x] implement a fixed delay node #231 
- [ ] implement a variable delay node #232 
- [x] write tests for delay node #233

**Comment by EyalLavi** [comment]
Moving to R4 following re-planning.

**Comment by nigelmegitt** [comment]
Variable delay node will not be in R2 - bumping to R3 as per the release plan as it stands today.

**Comment by nigelmegitt** [comment]
I've changed my view on variable delay nodes and the group has also agreed that there are no normative requirements for variable delay nodes that will be in the spec, so I consider the Delay node component implementation complete at this stage, for spec purposes anyway. Variable delay nodes can be considered to be new components - there are currently no issues open for them.
