### ISSUE TITLE
COMPONENT: EBU-TT-D encoder

### ISSUE THREAD

**Issue by EyalLavi** [ebu/ebu-tt-live-toolkit#30]
As a playout service provider, I want to convert EBU-TT-Live documents to EBU-TT-D documents so that I can distribute them to the end device

Input: sequence of part 3 documents
Output: sequence of EBU-TT-D documents

Subtasks:
- [x] Add EBU-TT-D XSD 1.1 to repository and update it if necessary #177
- [x] Create bindings (move EBU-TT-3 current bindings to a sensible place) #176
- [x] Conversion initiation logic and validation #174 
- [ ] Create EBU-TT-D conversion classes #170

**Comment by nigelmegitt** [comment]
This is mostly complete but I am considering pushing the remaining parts to a later milestone on the basis that the EBU-TT-D encoding is "good enough" for now, though clearly there are improvements that can be made.

**Comment by nigelmegitt** [comment]
Moved the last part of this out to a new issue for R3; the remainder of this is now complete for R2, so closing.
