### ISSUE TITLE
COMPONENT: Simple Part 3 consumer (Semantic validation)

### ISSUE THREAD

**Issue by frans-ebu** [ebu/ebu-tt-live-toolkit#42]
As a developer/playout service provider, I want to validate an EBU-TT Live sequence against the specification so that I know if they conform to the specification.

Input: Single part 3 doc or sequence of part 3 documents
Output: display of text with begin and end times and validation message(s)

It requires the following steps to be completed:
- [x] validation framework for semantic rules #72
- [x] live semantic validation #73
- [x] timing calculation(consumer)
  - [x] copy across timing constraints from BBC/kozma/consumerlogic branch #88
  - [x] calculate document computed begin and end times #89
  - [x] calculate resolved activation begin and end times #109
  - [x] document begin and end times should be in that order on the timeline according to R16
  - [x] write tests for correct resolution of activation time calculation
- [x] produce output
  - [x] generate output requirements - see #87
  - [x] write output

(this list is not yet complete)

**Comment by kozmaz87** [comment]
This is to be split into at least 3 other issues:

 * semantic validation framework
 * semantic validation for live elements
 * timing scenarios(consumer)
